### ISSUE TITLE
Connect to QUIDO from 2 APIs from same PC (ipv4)

### ISSUE THREAD

**Issue by Ales5475** [Papouchcom/spinel.net#4]
Hello,

I would like to ask if it is possible to connect from 2 APIs on the same PC to 1 QUIDO. I tried to use the demo and it is not able to do such a thing (second DEMO GUI throws):
CONNECT - err: [ci.Open() = false]

Why do I need it? Because I want view I/O status of QUIDO in user friendly GUI and simultaneously changing things from another APIs.

What is the purpose of "adr=254"? Is it what I need?

Thank you in advance.

Best Regards
Aleš Novotný

**Comment by Papouchcom** [comment]
What communication line do you use? 

**If communicating via Ethernet:**
- Spinel.NET uses TCP for communication and Quido unfortunately has only one connection. So the limitation to one connection is on Quido's side. When connection is busy, no one else can connect via TCP.
- The alternative is to use [http GET](https://en.papouch.com/http-get-in-i-o-quido-modules-how-to-do-it-p4040/) control instead of Spinel. This can in principle be used from multiple clients. (Status of inputs and outputs can then be [read via XML](https://en.papouch.com/what-information-can-you-get-from-xml-in-quido-p4042/).)

**If RS232, RS485 or USB:**
- In principle, it is not possible to open one port more than once, so practically the same restrictions apply as for TCP on Ethernet.
- Address 254 - the "universal address" - is used to address a single device on the communication bus. If there is a single device on the line, there is no need to know the address. However, this is mainly used when communicating over the RS485 bus.

If you see any limitations in http get, let us know. I believe it can be solved - we are the authors of the hardware and firmware.

**Comment by Ales5475** [comment]
Yeah, I am using Spinel. So, Spinel is completelly useless in my case. Ok, I will try to implement http GET.

Thank you for your advice and information in very fast time.
